*******************************************************
* inheritance-oecd - Stata deliverables (econometrics appendix)
* Focus: Inheritance & inter-vivos gifts (OECD 4300)
* Rule: OECD_REP stays in descriptive tables,
*       but excluded from 4310 vs 4320 split and placebo/randomization
* Stata: 12.0 compatible
*
* Outputs:
*   outputs/stata/tables/
*     debug_country_codes_raw.csv
*     tableS_levels_shares_2018_2022_stata.csv
*     tableT_split_4310_4320_2018_2022_stata.csv
*     tableA_spec_comparison_che_trend.csv
*     tableB_hausman_fe_re_simple.csv
*     tableB2_mundlak_cre_test.csv
*     tableC_placebo_diffs_<outcome>_<y0>_<y1>.csv
*     tableC_placebo_summary_<outcome>_<y0>_<y1>.csv
*     table_master_results.csv
*   outputs/stata/figures/
*     figC_placebo_<outcome>_<y0>_<y1>.png
*******************************************************

version 12.0
clear all
set more off
set scheme s1color

* --- Project root (Windows: use forward slashes) ---
global ROOT "C:/Users/eduar/Documents/inheritance-oecd"
cd "$ROOT"

* --- Folders ---
foreach f in "outputs/stata" "outputs/stata/figures" "outputs/stata/tables" "outputs/stata/logs" {
    cap mkdir "`f'"
}

capture log close
log using "outputs/stata/logs/stata_run.log", replace text

*******************************************************
* 0) Load data (generated by R pipeline)
*******************************************************
capture confirm file "data/processed/panel_taxmix.dta"
if _rc {
    di as error "Missing data/processed/panel_taxmix.dta"
    di as error "Run the R pipeline to export a Stata .dta (haven::write_dta, version=12)."
    log close
    exit 601
}

use "data/processed/panel_taxmix.dta", clear
compress

* --- Required vars checks ---
foreach v in country_code country_name year {
    capture confirm variable `v'
    if _rc {
        di as error "Variable '`v'' not found. Check R export."
        log close
        exit 602
    }
}

* Harmonize variable names (T_ vs t_) and (_T vs _t)
foreach k in 4000 4200 4300 4310 4320 {
    capture confirm variable T_`k'
    if _rc {
        capture confirm variable t_`k'
        if !_rc rename t_`k' T_`k'
    }
}

capture confirm variable _T
if _rc {
    capture confirm variable _t
    if !_rc rename _t _T
}

* Basic cleaning
replace country_code = upper(trim(country_code))
replace country_name = trim(country_name)

* DEBUG: export distinct raw country codes seen in DTA
preserve
keep country_code
duplicates drop
sort country_code
outsheet using "outputs/stata/tables/debug_country_codes_raw.csv", comma replace
restore

*******************************************************
* 0.1) Robust country filtering (Stata 12 safe)
* Prefer R-generated glossary: outputs/tables/country_iso3_glossary.csv
*******************************************************
local used_glossary = 0
capture confirm file "outputs/tables/country_iso3_glossary.csv"
if !_rc {
    preserve
    * Stata 12: use insheet (NOT import delimited)
    insheet using "outputs/tables/country_iso3_glossary.csv", comma clear names
    capture confirm variable country_code
    if _rc {
        di as error "Glossary found but no column named country_code. Fallback to ISO3 regex guard."
        restore
    }
    else {
        keep country_code
        replace country_code = upper(trim(country_code))
        duplicates drop
        tempfile keepcodes
        save "`keepcodes'", replace
        restore

        merge m:1 country_code using "`keepcodes'", keep(3) nogen
        local used_glossary = 1
        di as txt "Country filter: USED glossary outputs/tables/country_iso3_glossary.csv"
    }
}

if `used_glossary'==0 {
    di as error "Country filter: glossary not used; FALLBACK to ISO3 regex guard."
    quietly count
    local N0 = r(N)
    drop if country_code!="OECD_REP" & !regexm(country_code,"^[A-Z]{3}$")
    quietly count
    local N1 = r(N)
    di as txt "ISO3 guard fallback: kept `N1' obs (dropped `=`N0'-`N1'' obs)."
}

* Must have CHE for main comparisons
quietly count if country_code=="CHE"
if r(N)==0 {
    di as error "CHE not found after filtering."
    di as error "Check outputs/stata/tables/debug_country_codes_raw.csv and outputs/tables/country_iso3_glossary.csv"
    log close
    exit 604
}

*******************************************************
* Derived annual shares (used in econometrics/appendix)
*******************************************************
capture drop share4300_total share4300_in4000 share4200_in4000 shareother_in4000
gen double share4300_total   = 100 * T_4300 / _T     if _T > 0 & !missing(T_4300, _T)
gen double share4300_in4000  = 100 * T_4300 / T_4000 if T_4000 > 0 & !missing(T_4300, T_4000)
gen double share4200_in4000  = 100 * T_4200 / T_4000 if T_4000 > 0 & !missing(T_4200, T_4000)
gen double shareother_in4000 = 100 - share4300_in4000 - share4200_in4000 if !missing(share4300_in4000, share4200_in4000)

label var share4300_total  "T_4300 as % of total tax revenue (annual, %)"
label var T_4300           "Estate, inheritance & gift taxes (4300) (% of GDP)"

*******************************************************
* TABLE S (2018-2022): averages from mean levels (OECD_REP included)
*******************************************************
preserve
keep if inrange(year, 2018, 2022)
collapse (mean) T_4000 T_4200 T_4300 _T, by(country_code country_name)

gen double avg_4300_pct_gdp     = T_4300
gen double avg_4300_share_total = 100 * T_4300 / _T     if _T>0 & !missing(T_4300,_T)
gen double avg_4300_share_4000  = 100 * T_4300 / T_4000 if T_4000>0 & !missing(T_4300,T_4000)
gen double avg_4200_share_4000  = 100 * T_4200 / T_4000 if T_4000>0 & !missing(T_4200,T_4000)

outsheet country_code country_name avg_4300_pct_gdp avg_4300_share_total ///
    avg_4300_share_4000 avg_4200_share_4000 ///
    using "outputs/stata/tables/tableS_levels_shares_2018_2022_stata.csv", comma replace
restore

*******************************************************
* TABLE T (2018-2022): split 4300 into inheritance vs gifts (EXCLUDE OECD_REP)
* Residual logic:
* - If gifts missing but inheritance present -> gifts = residual
* - If inheritance missing but gifts present -> inheritance = residual
*******************************************************
preserve
keep if inrange(year, 2018, 2022)
drop if country_code=="OECD_REP"

gen byte has_4320_y = !missing(T_4320)
collapse (mean) T_4300 T_4310 T_4320 (max) has_4320_y, by(country_code country_name)

* Keep only where 4300 exists
keep if !missing(T_4300) & T_4300>0

gen double sh_inherit        = 100 * T_4310 / T_4300 if !missing(T_4310)
gen double sh_gifts_reported = 100 * T_4320 / T_4300 if !missing(T_4320)

gen double sh_gifts_or_resid = sh_gifts_reported
replace sh_gifts_or_resid = 100 - sh_inherit if missing(sh_gifts_or_resid) & !missing(sh_inherit)

gen double sh_inherit_or_resid = sh_inherit
replace sh_inherit_or_resid = 100 - sh_gifts_reported if missing(sh_inherit_or_resid) & !missing(sh_gifts_reported)

* Renormalize when sums ~100 (guards rounding)
gen double ssum = sh_inherit_or_resid + sh_gifts_or_resid
replace sh_inherit_or_resid = 100 * sh_inherit_or_resid / ssum if ssum>95 & ssum<105 & !missing(ssum)
replace sh_gifts_or_resid   = 100 * sh_gifts_or_resid   / ssum if ssum>95 & ssum<105 & !missing(ssum)

gen str80 note = ""
replace note = "CHE: gifts not separately reported (gifts shown as residual)" ///
    if country_code=="CHE" & missing(sh_gifts_reported) & !missing(sh_inherit_or_resid)
replace note = "No separate gifts series (4320 not reported)" if has_4320_y==0

outsheet country_code country_name sh_inherit_or_resid sh_gifts_or_resid sh_gifts_reported note ///
    using "outputs/stata/tables/tableT_split_4310_4320_2018_2022_stata.csv", comma replace

* Keep CHE split for master results (if present)
quietly summarize sh_inherit_or_resid if country_code=="CHE", meanonly
local che_inherit = r(mean)
quietly summarize sh_gifts_or_resid if country_code=="CHE", meanonly
local che_gifts = r(mean)
restore

*******************************************************
* MASTER RESULTS table (single file for Results chapter)
*******************************************************
tempname mh
tempfile master
postfile `mh' str22 block str18 outcome str11 period str46 item ///
    double estimate double se double p_value double N str80 note ///
    using "`master'", replace

* Add CHE split rows (descriptive) if available
post `mh' ("Descriptives") ("T_4300") ("2018-2022") ("CHE inheritance share in 4300 (%)") (`che_inherit') (.) (.) (.) ("from Table T")
post `mh' ("Descriptives") ("T_4300") ("2018-2022") ("CHE gifts share in 4300 (%)") (`che_gifts') (.) (.) (.) ("from Table T")

*******************************************************
* A) Two-way FE (country FE + year FE), cluster by country
* Baseline: che_trend = (year-1990) * 1{CHE}
* Also export estimator comparison (FE/RE/OLS).
*******************************************************
tempname spech
tempfile specout
postfile `spech' str18 outcome str28 estimator str20 term ///
    double b double se double p double N using "`specout'", replace

preserve
drop if country_code=="OECD_REP"
egen cc = group(country_code)
xtset cc year

gen byte   is_che    = (country_code=="CHE")
gen double c_year    = year - 1990
gen double che_trend = c_year * is_che

foreach Y in T_4300 share4300_total {

    * FE + year FE (cluster) [baseline]
    xtreg `Y' i.year che_trend, fe vce(cluster cc)
    scalar b1  = _b[che_trend]
    scalar se1 = _se[che_trend]
    scalar t1  = b1/se1
    scalar p1  = 2*ttail(e(df_r), abs(t1))
    post `spech' ("`Y'") ("FE + year FE (cluster)") ("CHE x trend") (b1) (se1) (p1) (e(N))

    post `mh' ("Two-way FE") ("`Y'") ("1990-2022") ("FE + year FE (cluster); term=CHE x trend") ///
        (b1) (se1) (p1) (e(N)) ("baseline spec")

    * RE + year FE (cluster) [comparison; uses z]
    xtreg `Y' i.year che_trend, re vce(cluster cc)
    scalar b2  = _b[che_trend]
    scalar se2 = _se[che_trend]
    scalar z2  = b2/se2
    scalar p2  = 2*normal(-abs(z2))
    post `spech' ("`Y'") ("RE + year FE (cluster)") ("CHE x trend") (b2) (se2) (p2) (e(N))

    * OLS + year FE (cluster) [comparison]
    reg `Y' i.year che_trend, vce(cluster cc)
    scalar b3  = _b[che_trend]
    scalar se3 = _se[che_trend]
    scalar t3  = b3/se3
    scalar p3  = 2*ttail(e(df_r), abs(t3))
    post `spech' ("`Y'") ("OLS + year FE (cluster)") ("CHE x trend") (b3) (se3) (p3) (e(N))
}

postclose `spech'
use "`specout'", clear
outsheet using "outputs/stata/tables/tableA_spec_comparison_che_trend.csv", comma replace
restore

*******************************************************
* B) Hausman FE vs RE (simple spec; no i.year)
* + Mundlak/CRE diagnostic (joint test of unit-mean terms)
*******************************************************
tempname hh creh
tempfile hausout creout
postfile `hh' str18 outcome str60 spec double chi2 double df double p_value using "`hausout'", replace
postfile `creh' str18 outcome str60 test double p_value double N using "`creout'", replace

foreach Y in T_4300 share4300_total {

    preserve
    drop if country_code=="OECD_REP"

    egen cc = group(country_code)
    xtset cc year

    gen byte   is_che      = (country_code=="CHE")
    gen double c_year      = year - 1990
    gen double che_trend   = c_year * is_che

    xtreg `Y' c_year che_trend, fe
    estimates store FE_simple

    xtreg `Y' c_year che_trend, re
    estimates store RE_simple

    local chi = .
    local dff = .
    local pp  = .
    capture noisily hausman FE_simple RE_simple, sigmamore
    if _rc==0 {
        local chi = r(chi2)
        local dff = r(df)
        local pp  = r(p)
    }

    * Mundlak/CRE: add unit means and test
    local pcre = .
    capture drop mean_c_year mean_che_trend
    bys cc: egen mean_c_year     = mean(c_year)
    bys cc: egen mean_che_trend  = mean(che_trend)

    xtreg `Y' c_year che_trend mean_c_year mean_che_trend, re
    capture noisily test mean_c_year mean_che_trend
    if _rc==0 {
        local pcre = r(p)
    }
    local Ncre = e(N)

    restore

    post `hh' ("`Y'") ("y ~ c_year + CHE*c_year; FE vs RE (simple)") (`chi') (`dff') (`pp')
    post `creh' ("`Y'") ("Mundlak/CRE: joint test of unit-mean terms") (`pcre') (`Ncre')

    post `mh' ("Hausman") ("`Y'") ("1990-2022") ("Hausman FE vs RE (simple; chi2)") (`chi') (`dff') (`pp') (.) ("estimate=chi2; se=df")
    post `mh' ("CRE/Mundlak") ("`Y'") ("1990-2022") ("Joint test of unit-mean terms (p)") (.) (.) (`pcre') (`Ncre') ("p_value only")
}

postclose `hh'
preserve
use "`hausout'", clear
outsheet using "outputs/stata/tables/tableB_hausman_fe_re_simple.csv", comma replace
restore

postclose `creh'
preserve
use "`creout'", clear
outsheet using "outputs/stata/tables/tableB2_mundlak_cre_test.csv", comma replace
restore

*******************************************************
* C) Exact placebo/randomization distribution
*    MAIN: 1990 2022
*    ROBUST: 2018 2022
*    Outcomes: mean T_4300 (% GDP) and mean share4300_total (% of total tax)
*******************************************************
foreach Y in T_4300 share4300_total {

    foreach P in "1990 2022" "2018 2022" {

        tokenize "`P'"
        local y0 = `1'
        local y1 = `2'

        preserve
        keep if inrange(year, `y0', `y1')
        drop if country_code=="OECD_REP"

        collapse (mean) `Y', by(country_code)
        drop if missing(`Y')

        quietly count if country_code=="CHE"
        if r(N)==0 {
            di as error "CHE missing for outcome `Y' in `y0'-`y1' after collapsing. Check missingness."
            restore
            log close
            exit 610
        }

        * Observed CHE - others
        quietly summarize `Y' if country_code=="CHE", meanonly
        scalar obs_che = r(mean)
        quietly summarize `Y' if country_code!="CHE", meanonly
        scalar obs_oth = r(mean)
        scalar obs_diff = obs_che - obs_oth
        scalar abs_obs  = abs(obs_diff)

        * Enumerate placebo diffs
        tempname ph
        tempfile placebo
        postfile `ph' str8 treated double diff using "`placebo'", replace

        levelsof country_code, local(codes)
        foreach c of local codes {
            quietly summarize `Y' if country_code=="`c'", meanonly
            local t = r(mean)
            quietly summarize `Y' if country_code!="`c'", meanonly
            local o = r(mean)
            post `ph' ("`c'") (`t' - `o')
        }
        postclose `ph'

        use "`placebo'", clear
        gen double absdiff = abs(diff)
        gen byte is_che = (treated=="CHE")

        count if absdiff >= abs_obs
        scalar p_exact = (r(N)+1) / (_N+1)

        * Save placebo table (sorted)
        gsort -diff
        outsheet treated diff absdiff is_che ///
            using "outputs/stata/tables/tableC_placebo_diffs_`Y'_`y0'_`y1'.csv", comma replace

        * One-line summary
        clear
        set obs 1
        gen str11 period = "`y0'-`y1'"
        gen str18 outcome = "`Y'"
        gen double obs_che_mean = obs_che
        gen double obs_oth_mean = obs_oth
        gen double obs_diff_che_minus_oth = obs_diff
        gen double p_exact_two_sided = p_exact
        outsheet using "outputs/stata/tables/tableC_placebo_summary_`Y'_`y0'_`y1'.csv", comma replace

        post `mh' ("Placebo") ("`Y'") ("`y0'-`y1'") ("Exact randomization p (two-sided); diff=CHE-others") ///
            (obs_diff) (.) (p_exact) (.) ("estimate=diff; p_value=p_exact")

               * Plot (CHE highlighted)  [readable + centered; Stata 12 safe]
        use "`placebo'", clear
        gsort -diff
        gen pos = _n
        gen byte is_che = (treated=="CHE")

        * Value labels in ranked order (matches gsort -diff)
        capture label drop poslbl
        forvalues j = 1/`=_N' {
            local cname = treated[`j']
            if `j'==1 {
                label define poslbl `j' "`cname'", replace
            }
            else {
                label define poslbl `j' "`cname'", add
            }
        }
        label values pos poslbl

        * --- Dynamic sizing: give each country vertical room (avoid label overlap) ---
        local N   = _N
        local xsz = 7.5
        local ysz = `N'*0.35
        if `ysz' < 9  local ysz = 9
        if `ysz' > 18 local ysz = 18

        * Label font scaling by N (Stata supports multipliers like *0.60)
        local labmult = 0.75
        if `N' > 25 local labmult = 0.60
        if `N' > 40 local labmult = 0.50

        * Strings for note (avoid nested quoting)
        local obs_str = string(obs_diff,"%9.4f")
        local p_str   = string(p_exact,"%9.4f")

        * Export pixel size consistent with physical inches (~300 dpi)
        local wpx = int(300*`xsz')
        local hpx = int(300*`ysz')

        twoway ///
            (bar diff pos if is_che==0, horizontal barwidth(0.70) ///
                lcolor(gs12) bcolor(gs12)) ///
            (bar diff pos if is_che==1, horizontal barwidth(0.70) ///
                lcolor(black) bcolor(black)), ///
            yscale(reverse) ///
            ylabel(1/`N', valuelabel angle(0) labsize(*`labmult')) ///
            xlabel(, labsize(small) format(%6.2f)) ///
            xline(0, lcolor(gs10)) ///
            title("Placebo distribution: treated minus others", size(small)) ///
            subtitle("Outcome: `Y'; `y0'-`y1' - CHE in black", size(small)) ///
            note("Observed CHE diff = `obs_str' ; exact p = `p_str'", size(tiny)) ///
            legend(off) ///
            ytitle("") ///
            xtitle("Treated minus others", size(small)) ///
            xsize(`xsz') ysize(`ysz') ///
            graphregion(color(white) margin(l=10 r=3 t=3 b=4)) ///
            plotregion(color(white) margin(l=2 r=2 t=1 b=1))

        graph export ///
            "outputs/stata/figures/figC_placebo_`Y'_`y0'_`y1'.png", ///
            replace width(`wpx') height(`hpx')

        * Optional (preferred for LaTeX zoom): vector PDF
        graph export ///
            "outputs/stata/figures/figC_placebo_`Y'_`y0'_`y1'.pdf", ///
            replace

        restore
    }
}

*******************************************************
* Finalize master results
*******************************************************
postclose `mh'
use "`master'", clear
outsheet using "outputs/stata/tables/table_master_results.csv", comma replace

log close
di as txt "DONE: Stata appendix outputs written to outputs/stata/{tables,figures}"
